import {
    Loader2,
    LogOut,
    Plus,
    CalendarIcon,
    CalendarClock,
    MoreHorizontal,
    Pencil,
    Trash2,
    Share2,
    Copy,
    CopyCheck,
    Github,
    Link,
    Bell,
    BellDot,
    CheckCheck,
    MessageSquare,
    Linkedin,
    Mail,
    PhoneCall,
    Settings,
    User2,
    Moon,
    Sun,
    SunMoon,
    UserX2,
    Eraser,
    Tv2
} from "lucide-react"

export const Icons = {
    loader: Loader2,
    logout: LogOut,
    plus: Plus,
    calendar: CalendarIcon,
    calendarClock: CalendarClock,
    more: MoreHorizontal,
    edit: Pencil,
    delete: Trash2,
    share: Share2,
    messageSquare: MessageSquare,
    userX: UserX2,
    copy: Copy,
    copyCheck: CopyCheck,
    github: Github,
    linkedin: Linkedin,
    bell: Bell,
    bellDot: BellDot,
    check: CheckCheck,
    mail: Mail,
    phone: PhoneCall,
    settings: Settings,
    user: User2,
    link: Link,
    moon: Moon,
    eraser: Eraser,
    sun: Sun,
    sunMoon: SunMoon,
    tv: Tv2
}